GET http://localhost:5000/api/v1/stores


###

POST http://localhost:5000/api/v1/stores
Content-Type: application/json

{
    "storeId": "0001",
    "address": "Vasant Vihar, New Delhi, Delhi"
}

